### ISSUE TITLE
Is there any provided pretrained STREAM module?

### ISSUE THREAD

**Issue by joannahong** [qiaott/MirrorGAN#6]
Are there any provided cnn_encoder.ckpt and rnn_decoder.ckpt for pretrained STEAM module?
There are pretrained STEM data but not STREAM.

**Comment by joannahong** [comment]
Also I tried to use the pretrained models (encoder-5-3000.pkl and decoder-5-3000.pkl) uploaded in the listed image captioning code, but the parameter shape does not match.

**Comment by FlowerRoad1996** [comment]
same question. It means I have to pretrain the module by myself?

**Comment by FlowerRoad1996** [comment]
How can I pretrain the STREAM module, any steps for work?

**Comment by qiaott** [comment]
> Also I tried to use the pre-trained models (encoder-5-3000.pkl and decoder-5-3000.pkl) uploaded in the listed image captioning code, but the parameter shape does not match.

Hi, it is normal that the parameter of pre-trained models in the listed image captioning code doesn't match, because we used the different caption dictionaries. The dictionary of our caption models built up based on the captions in the CUB dataset. The STREAM model is currently not available, it can be easily re-trained by using the image captioning code. To get a STREAM, please use the dictionary file 'bird_captions.pickle' provided in the pre-processed data to embed the sentences and train an image captioning model.
